### ISSUE TITLE
Taking too much time to show files

### ISSUE THREAD

**Issue by alexhorn76** [developeranaz/MEGA-INDEX-CLOUDFLARE#11]
Hi. I don't know why it takes too much time to see the files in deployed app

**Comment by alexhorn76** [comment]
I also restarted app and deployed it again but it wasn't helpful

**Comment by developeranaz** [comment]
> Hi. I don't know why it takes too much time to see the files in deployed app

There may be many possible causes.
Firstly heroku needs little wake-up time but wakeuptime is not too long or It maybe due to your root may contain a lot of files.I don't know what is the exact reason. Maybe its problems of mega blocking you ,I  had faced similar issue in one of my Mega account its rare. but i hadn't find a solution to fix that. 

Try different servers (Europe) in heroku and deploy it again, I don't know this would works or not just try it
or else try to use another Mega account. ; (

**Comment by alexhorn76** [comment]
Thanks man 
This app was so helpful for me
