### ISSUE TITLE
Private credentials

### ISSUE THREAD

**Issue by itssoap** [developeranaz/MEGA-INDEX-CLOUDFLARE#4]
Please remove your creds from a previous commit: https://github.com/developeranaz/Mega.nz-Rclone-Index-Heroku/commit/8ce28f5471e5dedcd4c1ab886948007e6c180c9f

**Comment by developeranaz** [comment]
I know that 🤗
Some of my previous commit history are exposed to public 😁
Now I've fixed it

I thought nobody wanted my repo, so I kept it public to continue testing for personal use

**Comment by itssoap** [comment]
Also, can you help me understand how the index is getting the gui. I tried rclone server locally but its a just a plain index without gui

**Comment by developeranaz** [comment]
The index on this repo is rclone's orginal serve index I have't modifed it.
May be you should use latest version of rclone and i will not recommend you to use 'apt install rclone ' command
Use other installation methods in https://rclone.org/install/

'apt install rclone' will give  only contain primitive index page in some linux distribution

**Comment by itssoap** [comment]
Ohh. Thanks for the info. Also I saw in Dockerfile that you are downloading rclone and rclone.1. What is rclone.1 for?

**Comment by developeranaz** [comment]
> Ohh. Thanks for the info. Also I saw in Dockerfile that you are downloading rclone and rclone.1. What is rclone.1 for?

Ok Here i am not using my official rclone/rclone docker base image
here i used nginx:latest as my base docker image
so in order to install rclone in that image i used
'Linux installation from precompiled binary method'
you can see the installation method at here https://rclone.org/install/

I got the file rclone.1 and rclone by extracting this zip https://downloads.rclone.org/rclone-current-linux-amd64.zip 
and copied to its locations as per the instructions given by rclone and given its permissions

**Comment by itssoap** [comment]
Okay. That resolves my issues. Thanks
